import { IScan } from '../models/Scan.model';
import { IFinding } from '../models/Finding.model';
import { generateShieldCode } from './shield.generator';

export interface MarkdownReportOptions {
  scan: IScan;
  findings: IFinding[];
}

export function generateMarkdownReport(options: MarkdownReportOptions): string {
  const { scan, findings } = options;
  const dateStr = scan.completedAt 
    ? new Date(scan.completedAt).toUTCString()
    : new Date(scan.createdAt).toUTCString();

  const failedFindings = findings.filter(f => !f.passed);
  const passedFindings = findings.filter(f => f.passed);

  const shieldCodeExpress = generateShieldCode({
    failedCheckIds: failedFindings.map(f => f.checkId),
    targetName: scan.target,
    framework: 'express'
  });

  const shieldCodeNext = generateShieldCode({
    failedCheckIds: failedFindings.map(f => f.checkId),
    targetName: scan.target,
    framework: 'next'
  });

  const lines: string[] = [];
  lines.push(`# AEGIS Security Audit Report`);
  lines.push(`## Target: \`${scan.target}\``);
  lines.push(`**Scan Time:** \`${dateStr}\``);
  lines.push(`**Overall Security Grade:** \`${scan.grade}\` (${scan.score}/100)\n`);

  lines.push(`### Summary Status`);
  lines.push(`| Status | Count |`);
  lines.push(`| :--- | :--- |`);
  lines.push(`| 🔴 Critical Issues | ${scan.summary.critical} |`);
  lines.push(`| 🟠 High Issues | ${scan.summary.high} |`);
  lines.push(`| 🟡 Medium Issues | ${scan.summary.medium} |`);
  lines.push(`| 🔵 Low Issues | ${scan.summary.low} |`);
  lines.push(`| 🟢 Passed Checks | ${scan.summary.passed} |`);
  lines.push(`\n---`);

  lines.push(`### Failed Checks (${failedFindings.length})`);
  if (failedFindings.length === 0) {
    lines.push(`✨ **Zero security gaps detected! Excellent posture.**\n`);
  } else {
    lines.push(`| Severity | Check | Category | Evidence |`);
    lines.push(`| :--- | :--- | :--- | :--- |`);
    failedFindings.forEach(f => {
      const severityEmoji = f.severity === 'critical' ? '🔴' : f.severity === 'high' ? '🟠' : f.severity === 'medium' ? '🟡' : '🔵';
      lines.push(`| ${severityEmoji} ${f.severity.toUpperCase()} | **${f.title}** | ${f.category} | \`${f.evidence.replace(/|/g, '\\|')}\` |`);
    });
    lines.push(`\n#### Remediation Details\n`);
    failedFindings.forEach(f => {
      lines.push(`* **${f.title}**: ${f.fix.text}`);
      if (f.fix.code) {
        lines.push(`  \`\`\`${f.fix.lang || 'http'}\n  ${f.fix.code.split('\n').join('\n  ')}\n  \`\`\``);
      }
    });
  }

  lines.push(`\n---`);

  lines.push(`### Passed Checks (${passedFindings.length})`);
  lines.push(`| Category | Check | Details |`);
  lines.push(`| :--- | :--- | :--- |`);
  passedFindings.forEach(f => {
    lines.push(`| ${f.category} | ${f.title} | \`${f.evidence.replace(/|/g, '\\|')}\` |`);
  });

  lines.push(`\n---`);
  lines.push(`### Generated AEGIS Shield Patches`);
  lines.push(`Use the following auto-generated middleware to patch the missing headers in your app:\n`);
  
  lines.push(`#### Express Middleware (\`aegis-shield.js\`)`);
  lines.push(`\`\`\`javascript\n${shieldCodeExpress}\n\`\`\`\n`);

  lines.push(`#### Next.js App Router Middleware (\`middleware.ts\`)`);
  lines.push(`\`\`\`typescript\n${shieldCodeNext}\n\`\`\`\n`);

  lines.push(`\n---\n*Report generated by [AEGIS Scanner](https://github.com/vedhr/CODES/Devlynix)*`);

  return lines.join('\n');
}
