export interface ShieldOptions {
  failedCheckIds: string[];
  targetName: string;
  framework: 'express' | 'next';
}

export function generateShieldCode(options: ShieldOptions): string {
  const { failedCheckIds, targetName, framework } = options;
  const dateStr = new Date().toISOString().split('T')[0];

  const headersMap: Record<string, { header: string; value: string; comment: string }> = {
    csp: {
      header: 'Content-Security-Policy',
      value: "default-src 'self'",
      comment: 'Mitigates XSS attacks by restricting resource loading origins'
    },
    hsts: {
      header: 'Strict-Transport-Security',
      value: 'max-age=31536000; includeSubDomains',
      comment: 'Forces all client browsers to communicate via encrypted HTTPS protocol only'
    },
    xfo: {
      header: 'X-Frame-Options',
      value: 'DENY',
      comment: 'Prevents clickjacking loops by blocking page embeds on other sites'
    },
    xcto: {
      header: 'X-Content-Type-Options',
      value: 'nosniff',
      comment: 'Disables browser MIME sniffing and enforces correct content-types'
    },
    refpol: {
      header: 'Referrer-Policy',
      value: 'strict-origin-when-cross-origin',
      comment: 'Protects user privacy by restricting referrer detail leaks on cross-origin requests'
    },
    permpol: {
      header: 'Permissions-Policy',
      value: 'camera=(), microphone=(), geolocation=()',
      comment: 'Disables browser feature permissions for camera, microphone, and location'
    }
  };

  // Filter only failed checks
  const missingHeaders = Object.keys(headersMap)
    .filter(id => failedCheckIds.includes(id))
    .map(id => headersMap[id]);

  if (framework === 'express') {
    const lines: string[] = [];
    lines.push(`// aegis-shield.js — generated by AEGIS for ${targetName} on ${dateStr}`);
    lines.push(`// Integration: app.use(require('./aegis-shield'))\n`);
    lines.push(`module.exports = function aegisShield(req, res, next) {`);

    if (missingHeaders.length === 0) {
      lines.push(`  // Target has no missing security headers. Standard shield config:`);
      lines.push(`  // All baseline policies are already set securely!`);
    } else {
      missingHeaders.forEach(item => {
        lines.push(`  // ${item.comment}`);
        lines.push(`  res.setHeader('${item.header}', "${item.value}");\n`);
      });
    }

    lines.push(`  next();`);
    lines.push(`};`);

    return lines.join('\n');
  } else {
    // Next.js middleware.ts
    const lines: string[] = [];
    lines.push(`// middleware.ts — generated by AEGIS for ${targetName} on ${dateStr}`);
    lines.push(`// Drop this file at the root of your Next.js src/ directory\n`);
    lines.push(`import { NextResponse } from 'next/server';`);
    lines.push(`import type { NextRequest } from 'next/server';\n`);
    lines.push(`export function middleware(request: NextRequest) {`);
    lines.push(`  const response = NextResponse.next();\n`);

    if (missingHeaders.length === 0) {
      lines.push(`  // No headers were missing during our scan. Standard shield is passive.`);
    } else {
      missingHeaders.forEach(item => {
        lines.push(`  // ${item.comment}`);
        lines.push(`  response.headers.set('${item.header}', "${item.value}");\n`);
      });
    }

    lines.push(`  return response;`);
    lines.push(`}\n`);
    lines.push(`// Match all paths except API, public static assets, and dev files`);
    lines.push(`export const config = {`);
    lines.push(`  matcher: ['/((?!api|_next/static|_next/image|favicon.ico).*)'],`);
    lines.push(`};`);

    return lines.join('\n');
  }
}
